name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
include-pre-releases: true

change-template: "- $TITLE (#$NUMBER)"

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - enhancement
  patch:
    labels:
      - patch
      - bug
      - maintenance
      - refactor
  default: patch

categories:
  - title: "Features"
    labels:
      - enhancement

  - title: "Bug Fixes"
    labels:
      - bug

  - title: "UI / UX"
    labels:
      - ui
      - ux

  - title: "Performance"
    labels:
      - performance

  - title: "Documentation"
    labels:
      - documentation

  - title: "Internal"
    labels:
      - maintenance
      - refactor

template: |
  ## What's Changed

  $CHANGES
